name: "lint"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-setup-action@v1
        with:
          version: latest

      - name: Check formatting
        run: buf format --diff --exit-code

      - uses: bufbuild/buf-lint-action@v1
